Week two task
Tech-Shark/syntax pull request #8
Opened 2024-11-25 09:03 UTC by onfranciis

- [x] Create credit
- [x] Create admin
- [x] Reorganise thead_local
- [x] Create setting

2024-11-26 23:15 UTC, ogbanugot requested changes

2024-11-26 23:15 UTC, ogbanugot commented on src/syntax_backend/src/schema/setting.rs
> +pub struct Setting {
Hi @onfranciis I don't understand the purpose of this schema. What's the idea here please, I don't recall this being part of what we discussed.

2024-11-26 23:15 UTC, ogbanugot commented on src/syntax_backend/src/service/credit.rs
> +    match SETTING_MAP.with(|map| map.borrow().get(&SETTING_KEY.to_string())) {
If SETTING_KEY is supposed to be an API_KEY then perhaps I see what you were going for, but then I already mentioned that we won't be doing it this way. We should instead check that the identity calling these admin endpoints belongs to an AdminMap which should contain theidentities that are admins.

2024-11-26 23:15 UTC, ogbanugot commented on src/syntax_backend/src/service/cv.rs
>  async fn analyze_cv(principal: String, request: CVUserInput) -> CVResponse {
How come there are no checks for credit usage in the CV service?  Every time a user tries to analyze a CV, we should check the credit usage and deduct. Why is the logic for that not here on the CV service endpoints?

2024-11-26 23:15 UTC, ogbanugot commented on src/syntax_backend/src/schema/admin.rs
> +pub enum AdminPlan {
Change to `AdminRole`

2024-11-26 23:18 UTC, ogbanugot commented
Hey @onfranciis this doesn't really implement most of what we discussed. These are the key points we discussed:

1. A service endpoint to tie a user to a subscription tier. Here we are assigning a number of credits (based on the tier type) to this user.

Create a service ‘Credits’
/add_credits (registering credits for a user based on the tier, check if they have credits already and increment based on the tier.)
/get_tiers => returns the available tiers (and credits)

2. Admin Service 
/set_tiers => set the number of credits per $ for each tier.

3. We need to handle managing these credits for each request. We need to check that the user still has enough credits to make a request. And we need to decrement their credit count each time a (CV Analyze) request is made. 

4. We need to remove the identity from service requests and make use of the ICP caller method to fetch the identity (see here https://github.com/Tech-Shark/syntax/blob/f446a67610dcbbccd34e852482ebb61664a16085/src/syntax_backend/src/lib.rs#L13)

2024-11-29 13:49 UTC, onfranciis commented on src/syntax_backend/src/schema/setting.rs
> +pub struct Setting {
This struct will be used in holding the config/settings related to various parts of this app. This data can be set and updated by only an admin. For example, the `max_freemium_users` is used to know how many people we want to accomodate on the free tier in the app. An admin might decide to reduce or increase the limit.

2024-12-02 08:24 UTC, ogbanugot approved these changes

2024-12-02 10:56 UTC, merged